
# Use this to load one of the GitHub Pages themes here:
#   https://pages.github.com/themes/
#theme: jekyll-theme-architect

# Or you can load any Jekyll theme from its GitHub repository:
remote_theme: Trybnetic/minimalist

repository: peterwwillis/github-pages-jekyll-base
url: https://peterwwillis.github.io
title: My Jekyll Site
description: 'Just my Jekyll site'

plugins:
    - jekyll-sitemap

encoding: utf-8

# We need to exclude at least the 'rvm' directory, because there are some
# Markdown examples which have bad UTF-8 and kill Jekyll. Also, extra files
# slow down the generation and creates pages we don't want.
# Note: Make sure the * character is in quotes! Yaml is picky.
exclude:
    - .bundle
    - vendor
    - rvm

