source 'https://rubygems.org'
gem 'jekyll', '= 3.7.4' , :group => :jekyll_plugins
gem 'jekyll-sass-converter', '= 1.5.2' , :group => :jekyll_plugins
gem 'kramdown', '= 1.17.0' , :group => :jekyll_plugins
gem 'jekyll-commonmark-ghpages', '= 0.1.5' , :group => :jekyll_plugins
gem 'liquid', '= 4.0.0' , :group => :jekyll_plugins
gem 'rouge', '= 2.2.1' , :group => :jekyll_plugins
gem 'github-pages-health-check', '= 1.16.1' , :group => :jekyll_plugins
gem 'jekyll-redirect-from', '= 0.14.0' , :group => :jekyll_plugins
gem 'jekyll-sitemap', '= 1.2.0' , :group => :jekyll_plugins
gem 'jekyll-feed', '= 0.11.0' , :group => :jekyll_plugins
gem 'jekyll-gist', '= 1.5.0' , :group => :jekyll_plugins
gem 'jekyll-paginate', '= 1.1.0' , :group => :jekyll_plugins
gem 'jekyll-coffeescript', '= 1.1.1' , :group => :jekyll_plugins
gem 'jekyll-seo-tag', '= 2.5.0' , :group => :jekyll_plugins
gem 'jekyll-github-metadata', '= 2.12.1' , :group => :jekyll_plugins
gem 'jekyll-avatar', '= 0.6.0' , :group => :jekyll_plugins
gem 'jekyll-remote-theme', '= 0.3.1' , :group => :jekyll_plugins
gem 'jemoji', '= 0.10.2' , :group => :jekyll_plugins
gem 'jekyll-mentions', '= 1.4.1' , :group => :jekyll_plugins
gem 'jekyll-relative-links', '= 0.6.0' , :group => :jekyll_plugins
gem 'jekyll-optional-front-matter', '= 0.3.0' , :group => :jekyll_plugins
gem 'jekyll-readme-index', '= 0.2.0' , :group => :jekyll_plugins
gem 'jekyll-default-layout', '= 0.1.4' , :group => :jekyll_plugins
gem 'jekyll-titles-from-headings', '= 0.5.1' , :group => :jekyll_plugins
gem 'listen', '= 3.1.5' , :group => :jekyll_plugins
gem 'activesupport', '= 4.2.10' , :group => :jekyll_plugins
gem 'jekyll-swiss', '= 0.4.0' , :group => :jekyll_plugins
gem 'minima', '= 2.5.0' , :group => :jekyll_plugins
gem 'jekyll-theme-primer', '= 0.5.3' , :group => :jekyll_plugins
gem 'jekyll-theme-architect', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-cayman', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-dinky', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-hacker', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-leap-day', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-merlot', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-midnight', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-minimal', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-modernist', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-slate', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-tactile', '= 0.1.1' , :group => :jekyll_plugins
gem 'jekyll-theme-time-machine', '= 0.1.1' , :group => :jekyll_plugins
gem 'github-pages', '= 197' , :group => :jekyll_plugins
gem 'html-pipeline', '= 2.10.0' , :group => :jekyll_plugins
gem 'sass', '= 3.7.3' , :group => :jekyll_plugins
gem 'safe_yaml', '= 1.0.5' , :group => :jekyll_plugins
gem 'nokogiri', '= 1.8.5' , :group => :jekyll_plugins
